#!/usr/bin/env python3
# Part 3: NVDA + SOXL panels.
import json

with open('data/market.json') as f:
    d = json.load(f)

p = d['positions']['nvda']
p.update({
    'price': '$224.58',
    'day_arrow': '▼', 'day_en': '−0.41% yesterday', 'day_ko': '어제 −0.41%', 'day_dir': 'dn',
    'week_arrow': '▲', 'week_en': '≈ +2.4% past five days', 'week_ko': '최근 5거래일 ≈ +2.4%', 'week_dir': 'up',
    'month_arrow': '▲', 'month_en': '≈ +1.7% so far in September', 'month_ko': '9월 들어 ≈ +1.7%', 'month_dir': 'up',
    'drawdown_arrow': '▼', 'drawdown': '≈ 5.1%', 'drawdown_dir': 'dn',
    'drawdown_fact_en': '≈ 5.1%', 'drawdown_fact_ko': '≈ 5.1%',
    'take_en': 'The summit passed quietly', 'take_ko': '정상회담은 조용히 지나감', 'take_tone': 'c-neu',
    'week_fact_en': 'up ≈ 2.4%', 'week_fact_ko': '≈ 2.4% 상승',
})
p['note_en'] = '<b>Yesterday the shares slipped 0.41% to $224.58 — a second straight dip, this one small, on a day the whole chip group fell hard in the morning and climbed all the way back.</b> The shares were down about 2% at their worst before recovering most of it with the market. And the event this share had been waiting for all month has now passed: the President and China’s leader met, dined with technology chiefs — <b>Jensen Huang sat at the head table</b> — exchanged warm toasts, and <b>announced nothing about chips or export rules in either direction</b>. For a share that has moved more on Washington’s China policy than on any earnings report for two years, no news cuts both ways: the hoped-for opening did not come, and neither did a new restriction. The question the summit was supposed to answer is simply still open. The shares sit about <b>5.1%</b> below their May record, are worth about <b>$5.4 trillion</b>, and trade at roughly <b>28.4 times</b> the past year’s profits. The next hard chip numbers arrive <b>Wednesday, when Micron reports</b>; Nvidia’s own results are not until November.'
p['note_ko'] = '<b>어제 주가는 0.41% 내린 224.58달러로 마쳤습니다. 이틀 연속 하락이지만 이번에는 소폭이고, 반도체 업종 전체가 아침에 크게 밀렸다가 전부 되오른 날이었습니다.</b> 주가는 최악에 2%쯤 내렸다가 시장과 함께 대부분 회복했습니다. 그리고 이 주식이 한 달 내내 기다려 온 행사가 이제 지나갔습니다. 대통령과 중국 지도자가 만나 기술 기업 대표들과 만찬을 했고 — <b>젠슨 황이 헤드테이블에 앉았습니다</b> — 따뜻한 건배사를 주고받았지만, <b>반도체나 수출 규정에 대해서는 어느 방향으로도 발표하지 않았습니다.</b> 2년 동안 어떤 실적 발표보다 워싱턴의 중국 정책에 크게 움직여 온 주식에, 무소식은 양쪽으로 읽힙니다. 바라던 개방도 오지 않았고, 새 규제도 오지 않았습니다. 정상회담이 답해 줄 것 같던 질문은 그냥 열려 있는 채입니다. 주가는 5월 기록보다 약 <b>5.1%</b> 아래에 있고, 회사 가치는 약 <b>5.4조 달러</b>이며, 지난 1년 이익의 약 <b>28.4배</b>에 거래됩니다. 다음 확실한 반도체 숫자는 <b>수요일 마이크론 실적</b>이고, 엔비디아 자신의 실적은 11월에야 나옵니다.'
p['news_en'] = [
    {'dt': 'Sep 24', 'tx': '<b>Slipped 0.41% to $224.58 — a second straight dip, on a day the chip group went from down more than 2% to a hair higher.</b> The White House summit ended with <b>Jensen Huang at the state dinner’s head table</b> and <b>no announcement on chips or export rules either way</b>. The ten-year rate closed at a second straight 2007-high. <b>Micron reports next Wednesday</b>; Nvidia’s own results are in November.'},
    p['news_en'][0], p['news_en'][1], p['news_en'][2],
]
p['news_ko'] = [
    {'dt': '9월 24일', 'tx': '<b>0.41% 내린 224.58달러 — 이틀 연속 하락이고, 반도체 업종이 2% 넘는 하락에서 살짝 오른 자리까지 되돌아온 날입니다.</b> 백악관 정상회담은 <b>국빈 만찬 헤드테이블의 젠슨 황</b>과 함께, <b>반도체와 수출 규정에 대한 어느 방향의 발표도 없이</b> 끝났습니다. 10년물 금리는 이틀 연속 2007년 이후 최고 종가를 썼습니다. <b>마이크론이 다음 주 수요일</b> 실적을 내고, 엔비디아 자신의 실적은 11월입니다.'},
    p['news_ko'][0], p['news_ko'][1], p['news_ko'][2],
]
p['verdict_en'] = '<b>What I’d watch first: Micron’s results next Wednesday, September 30 — the first hard figures behind the memory story that has led the whole chip rise.</b> Strong memory demand is chip demand by another name, so a good report supports this share too — but remember the twist this page keeps noting: Nvidia buys memory rather than selling it, so the shortage that makes Micron rich raises Nvidia’s own costs. Second, <b>rates</b>: at about <b>28.4 times</b> the past year’s profits this share is priced on money expected years from now, and the ten-year has closed at a 2007-high two days running, with the inflation figure that could move it further due the same Wednesday. Third, <b>Washington</b>: the summit answered nothing, so the chip-export question that has moved this share more than any earnings report simply stays open — it can return any week, in either direction. Nvidia’s own results are not until <b>November</b>; until then this share lives on other people’s news. And the standing note does not change: whatever chips do, <b>SOXL does about three times as much</b> — yesterday chips visited −2.2% during the day and SOXL visited −6.4%, before both climbed back.'
p['verdict_ko'] = '<b>가장 먼저 지켜볼 것: 다음 주 수요일, 9월 30일 마이크론 실적입니다. 반도체 상승 전체를 이끌어 온 메모리 이야기 뒤의 첫 확실한 숫자입니다.</b> 강한 메모리 수요는 이름만 다른 반도체 수요이니 좋은 실적은 이 주식에도 힘이 됩니다. 다만 이 페이지가 계속 적어 온 반전을 기억하십시오. 엔비디아는 메모리를 파는 쪽이 아니라 사는 쪽이라, 마이크론을 부자로 만드는 부족은 엔비디아 자신의 비용을 올립니다. 둘째, <b>금리</b>입니다. 지난 1년 이익의 약 <b>28.4배</b>라는 값은 몇 년 뒤의 돈에 매겨진 값인데, 10년물이 이틀 연속 2007년 이후 최고 종가를 썼고, 그것을 더 움직일 수 있는 물가 수치가 같은 수요일에 나옵니다. 셋째, <b>워싱턴</b>입니다. 정상회담이 아무것도 답하지 않았으니, 어떤 실적 발표보다 이 주식을 크게 움직여 온 반도체 수출 질문은 그냥 열려 있습니다. 어느 주에든, 어느 방향으로든 돌아올 수 있습니다. 엔비디아 자신의 실적은 <b>11월</b>에야 나오니, 그때까지 이 주식은 남의 소식으로 삽니다. 그리고 항상 붙는 메모는 그대로입니다. 반도체가 무엇을 하든 <b>SOXL은 그 세 배쯤</b>을 합니다. 어제 반도체는 장중 −2.2%까지, SOXL은 −6.4%까지 갔다가 함께 되올랐습니다.'
p['plain_en'] = 'Nvidia makes the chips that power artificial intelligence. It is one of the most valuable companies on earth, worth about <b>$5.4 trillion</b>. <b>Yesterday the shares slipped 0.41% to $224.58</b> — a second small dip, on a day the whole chip group fell hard in the morning and recovered by the close. The month’s big political event has passed: the White House summit with China’s leader ended with warm words, Nvidia’s chief executive at the state dinner, and <b>no decision on chip exports in either direction</b> — the question that matters most to this share stays open. Over five trading days the shares are up about <b>2.4%</b>. They sit about <b>5.1%</b> below their May record and are priced at roughly <b>28.4 times</b> the past year’s profits, with their own next report in November.'
p['plain_ko'] = '엔비디아는 인공지능을 움직이는 반도체를 만듭니다. 지구에서 가장 값비싼 회사 중 하나로, 회사 가치는 약 <b>5.4조 달러</b>입니다. <b>어제 주가는 0.41% 내린 224.58달러였습니다.</b> 이틀째의 소폭 하락이고, 반도체 업종 전체가 아침에 크게 밀렸다가 마감까지 회복한 날이었습니다. 이번 달의 큰 정치 행사는 지나갔습니다. 중국 지도자와의 백악관 정상회담은 따뜻한 말과 국빈 만찬의 엔비디아 최고경영자, 그리고 <b>어느 방향으로도 내려지지 않은 반도체 수출 결정</b>으로 끝났습니다. 이 주식에 가장 중요한 질문은 열려 있는 채입니다. 최근 5거래일로 주가는 약 <b>2.4%</b> 올라 있습니다. 5월 기록보다 약 <b>5.1%</b> 아래이고, 지난 1년 이익의 약 <b>28.4배</b>에 거래되며, 다음 실적 발표는 11월입니다.'
p['bull_en'] = 'The demand is still other companies’ money, and it keeps getting bigger. <b>Intel</b> is reported to have more demand than it can build; <b>South Korea’s</b> customs data shows chip exports at roughly three times last year’s pace; <b>Oracle</b> has committed <b>$90–95 billion</b> to equipment this year; <b>Dell</b> holds a record backlog of AI servers that run on Nvidia chips; and <b>Micron</b> reports <b>next Wednesday</b>, with strong memory demand being chip demand by another name. Nvidia’s own chief executive said this month the company expects to sell <b>twice as many chips next year</b> — his forecast, but every hard number around it points the same way. China sales are still counted at close to nothing in Nvidia’s own guidance, so anything Washington ever concedes on chip exports remains nearly pure upside — and the summit, for all it failed to deliver, took nothing away either. At about <b>28.4 times</b> profits, the price asks less of the future than it did in the spring.'
p['bull_ko'] = '수요는 여전히 다른 회사들의 돈이고, 계속 커지고 있습니다. <b>인텔</b>은 만들 수 있는 양보다 수요가 많다고 전해집니다. <b>한국</b> 관세청 자료는 반도체 수출이 작년의 세 배쯤 되는 속도라는 것을 보여 줍니다. <b>오라클</b>은 올해 장비에 <b>900억~950억 달러</b>를 약속했고, <b>델</b>은 엔비디아 반도체로 돌아가는 AI 서버 주문을 기록적으로 쌓아 두고 있으며, <b>마이크론</b>은 <b>다음 주 수요일</b> 실적을 냅니다. 강한 메모리 수요는 이름만 다른 반도체 수요입니다. 엔비디아 최고경영자는 이번 달, 내년에 반도체를 <b>두 배로 팔</b> 것으로 본다고 말했습니다. 본인의 전망이지만, 주변의 확실한 숫자들이 모두 같은 방향을 가리킵니다. 엔비디아 자신의 전망에는 중국 매출이 여전히 거의 0으로 잡혀 있어서, 워싱턴이 언젠가 수출에서 무엇을 양보하든 거의 순수한 보너스로 남아 있습니다. 그리고 정상회담은 아무것도 내놓지 못했지만, 아무것도 가져가지도 않았습니다. 이익의 약 <b>28.4배</b>라는 값은 봄보다 미래에 덜 기대는 값입니다.'
p['bear_en'] = '<b>The two forces that can move this price without a single piece of company news — rates and Washington — both spoke this week, and neither said anything kind.</b> The ten-year has closed at a 2007-high two days running, and at about <b>28.4 times</b> profits with no results until <b>November</b>, this share has two months to live on other people’s news. The summit came and went without the chip-export opening part of this month’s rise had quietly assumed — the hope was spent, and nothing was bought with it. The market also keeps paying the companies around Nvidia more generously than Nvidia: <b>AMD</b> is valued above <b>$1 trillion</b>, memory is where the gains keep going, and the memory shortage raises Nvidia’s own costs. And the slow-down argument from the heads of the leading AI labs has not been withdrawn — the month opened with a reminder of what that costs: chips down <b>5.63%</b> in a day, Nvidia down <b>3.36%</b>, SOXL down about <b>17%</b>.'
p['bear_ko'] = '<b>회사 소식 하나 없이 이 주가를 움직일 수 있는 두 힘 — 금리와 워싱턴 — 이 이번 주에 둘 다 입을 열었는데, 어느 쪽도 다정한 말은 아니었습니다.</b> 10년물은 이틀 연속 2007년 이후 최고 종가를 썼고, 이익의 약 <b>28.4배</b>인데 실적은 <b>11월</b>까지 없으니, 이 주식은 두 달을 남의 소식으로 살아야 합니다. 정상회담은 이번 달 상승이 조용히 가정하고 있던 반도체 수출 개방 없이 지나갔습니다. 기대는 썼는데, 그것으로 산 것은 없습니다. 시장이 엔비디아보다 엔비디아 주변 회사들에 더 후하게 지급하는 것도 그대로입니다. <b>AMD</b>는 <b>1조 달러</b> 위에서 평가받고, 상승이 계속 몰리는 곳은 메모리이며, 메모리 부족은 엔비디아 자신의 비용을 올립니다. 그리고 선도 AI 연구소 경영진의 속도 조절 주장은 철회되지 않았습니다. 이번 달은 그것이 얼마짜리인지 일깨우며 시작했습니다. 반도체가 하루 <b>5.63%</b>, 엔비디아가 <b>3.36%</b>, SOXL이 약 <b>17%</b> 내린 날이었습니다.'

p = d['positions']['soxl']
p.update({
    'price': '$146.33',
    'day_arrow': '▲', 'day_en': '+0.05% yesterday', 'day_ko': '어제 +0.05%', 'day_dir': 'up',
    'week_arrow': '▲', 'week_en': '≈ +27.4% past five days', 'week_ko': '최근 5거래일 ≈ +27.4%', 'week_dir': 'up',
    'month_arrow': '▲', 'month_en': '≈ +29.7% so far in September', 'month_ko': '9월 들어 ≈ +29.7%', 'month_dir': 'up',
    'drawdown_arrow': '▼', 'drawdown': '≈ 51.5%', 'drawdown_dir': 'dn',
    'drawdown_fact_en': '≈ 51.5%', 'drawdown_fact_ko': '≈ 51.5%',
    'take_en': 'Danger — read this one', 'take_ko': '위험 — 꼭 읽어보세요', 'take_tone': 'c-risk',
    'week_fact_en': 'up ≈ 27.4%', 'week_fact_ko': '≈ 27.4% 상승',
})
p['note_en'] = '<b>It closed up 0.05% at $146.33 — a flat day on the board, and nothing like a flat day to live through.</b> In the first hour it was down more than <b>6%</b>: chip shares opened more than 2% lower, and this fund triples whatever they do. It then climbed all the way back as the market recovered on the report of US-Iran talks. That is the whole product in one session — the close reads calm, and the ride was a 6% hole and a 6% climb between breakfast and lunch. The five-day figure is still enormous: about <b>+27.4%</b> against the chip index’s <b>+9.0%</b>, slightly more than a simple triple, because most of those days rose in a line and the daily reset compounds a straight run in the holder’s favour. The same caveat travels with it: the window begins three sessions after the mid-September crash bottom; measured from the Friday before that weekend, the rise is about <b>+20.1%</b>. Both are true — know which one you are being shown. The hole above is barely changed: about <b>51.5%</b> below its 1-year high, needing about <b>+106%</b> to get back. The next dated test reaches this fund at triple size: <b>Micron’s results and the Fed’s inflation figure, both next Wednesday</b>. It took <b>57%</b> in a flat July.'
p['note_ko'] = '<b>0.05% 오른 146.33달러로 마감 — 표 위에서는 제자리 하루이지만, 겪어 내기에는 전혀 제자리가 아니었습니다.</b> 첫 한 시간 동안 <b>6%</b> 넘게 내려 있었습니다. 반도체 주식이 2% 넘게 낮게 출발했고, 이 펀드는 그들이 하는 일의 세 배를 하기 때문입니다. 그 뒤 미국-이란 협상 보도에 시장이 회복하면서 전부 되올랐습니다. 이것이 이 상품의 전부를 담은 하루입니다. 종가는 차분해 보이지만, 실제 여정은 아침과 점심 사이의 6% 구덩이와 6% 등반이었습니다. 5일 숫자는 여전히 거대합니다. 반도체 지수 <b>+9.0%</b>에 대해 약 <b>+27.4%</b>로, 단순한 세 배보다 조금 많습니다. 닷새 대부분이 끊기지 않고 올라, 매일 리셋이 곧은 구간을 보유자에게 유리한 복리로 만들었기 때문입니다. 같은 단서도 함께 갑니다. 이 구간은 9월 중순 폭락 바닥에서 세 거래일 지난 곳에서 시작합니다. 그 주말 전 금요일부터 재면 약 <b>+20.1%</b>입니다. 둘 다 사실이니, 어느 쪽을 보고 있는지 아는 것이 중요합니다. 위에 뚫린 구멍은 거의 그대로입니다. 1년 최고가보다 약 <b>51.5%</b> 아래이고, 돌아가려면 약 <b>+106%</b>가 필요합니다. 다음 날짜 박힌 시험은 세 배 크기로 이 펀드에 닿습니다. <b>다음 주 수요일의 마이크론 실적과 연준 물가 수치</b>입니다. 제자리걸음이던 7월에는 <b>57%</b>를 가져갔습니다.'
p['note_head_en'] = 'Re-checked this morning, before the market opened, and confirmed for the thirty-second time in a row. Thursday’s close is $146.33, up 0.05%. Two independent feeds give the identical full day’s record: open $138.47, high $147.20, low $136.90, close $146.33. On a day this flat the closing arithmetic disappears into rounding — the plain chip fund finished 0.06% higher, three times that is 0.19%, and this fund delivered 0.05%, a gap of about a seventh of a point, far inside anything that matters. The convincing check is the shape of the day: at its worst the chip fund was down about 2.2%, three times that is about 6.6%, and this fund’s low was 6.4% below Wednesday’s close — the machine tracked all the way down and all the way back. The week still needs its chaperone, with new numbers: about +27.4% over five trading days against the chip index’s +9.0% — slightly more than a simple triple of +27.1%, because four of the five days rose and each day’s tripled gain compounded on a bigger pot; chaining three times each day’s index move predicts about +28.3%, a residual under a point, all reported as approximate. The window still flatters: it starts three sessions off the bottom of the mid-September crash, and from the Friday before that weekend the rise is about +20.1%. Know which figure you are being shown.'
p['note_head_ko'] = '오늘 아침 장이 열리기 전에 다시 확인했고, 연속 서른두 번째로 이상이 없었습니다. 목요일 종가는 0.05% 오른 146.33달러입니다. 독립된 두 데이터가 하루 기록 전체를 똑같이 보여 줍니다. 시가 138.47, 고가 147.20, 저가 136.90, 종가 146.33달러입니다. 이렇게 제자리인 날에는 종가 산수가 반올림 속으로 사라집니다. 일반 반도체 펀드는 0.06% 올랐고, 그 세 배는 0.19%이며, 이 펀드는 0.05%를 냈습니다. 약 7분의 1포인트의 차이로, 의미 있는 어떤 수준에도 한참 못 미칩니다. 설득력 있는 확인은 하루의 모양입니다. 반도체 펀드는 최악에 2.2%쯤 내려 있었고, 그 세 배는 약 6.6%인데, 이 펀드의 저점은 수요일 종가보다 6.4% 아래였습니다. 기계는 내려가는 길도, 되올라오는 길도 그대로 따라갔습니다. 주간 숫자에는 여전히 보호자가 필요하고, 숫자는 새것입니다. 최근 5거래일 약 +27.4%, 반도체 지수는 +9.0%입니다. 단순한 세 배인 +27.1%보다 조금 많습니다. 닷새 중 나흘이 올라, 매일의 세 배 수익이 더 커진 원금 위에 쌓였기 때문입니다. 매일 지수 움직임의 세 배를 이어 붙이면 약 +28.3%가 나오니 오차는 1포인트 미만이고, 모두 근사치로 적습니다. 이 구간은 여전히 실제보다 좋아 보입니다. 9월 중순 폭락 바닥에서 세 거래일 지난 곳에서 시작하고, 그 주말 전 금요일부터 재면 약 +20.1%입니다. 지금 보고 있는 숫자가 어느 쪽인지 아는 것이 중요합니다.'
p['day_caveat_en'] = 'Yesterday’s <b>+0.05%</b> was checked four ways, as this holding always is. First, the fund’s own daily record: open <b>$138.47</b>, high <b>$147.20</b>, low <b>$136.90</b>, close <b>$146.33</b> against Wednesday’s <b>$146.25</b>. Two independent feeds give that whole row to the cent. Second, the shape of the day: it was down more than <b>6%</b> in the first hour and recovered all of it — the close, not the low, is the day’s number, and yesterday that rule worked in the fund’s favour for once. Third, the tripling: the plain chip fund rose <b>0.06%</b>, three times that is <b>0.19%</b>, and this fund rose <b>0.05%</b> — on a day this flat the difference is rounding noise; the intraday lows fit the triple more tightly, about <b>6.4%</b> down against three times the chip fund’s 2.2%. Fourth, the week: about <b>+27.4%</b> across five days against the index’s <b>+9.0%</b> — slightly more than a simple triple of about +27.1%; chaining each day’s tripled move predicts about <b>+28.3%</b>, so the fit is loose by under a point and every week figure here is approximate. That window starts three sessions off the bottom of the mid-September crash; from the Friday before the crash the rise is about <b>+20.1%</b>.'
p['day_caveat_ko'] = '어제의 <b>+0.05%</b>는 이 종목이 늘 그렇듯 네 가지 방법으로 확인했습니다. 첫째, 펀드 자신의 하루 기록입니다. 시가 <b>138.47달러</b>, 고가 <b>147.20달러</b>, 저가 <b>136.90달러</b>, 종가 <b>146.33달러</b>, 수요일 종가는 <b>146.25달러</b>입니다. 독립된 두 데이터가 이 줄 전체를 센트 단위까지 똑같이 보여 줍니다. 둘째, 하루의 모양입니다. 첫 한 시간에 <b>6%</b> 넘게 내렸다가 전부 회복했습니다. 하루의 숫자는 저점이 아니라 종가이고, 어제는 모처럼 그 규칙이 펀드에 유리하게 작동했습니다. 셋째, 세 배 확인입니다. 일반 반도체 펀드는 <b>0.06%</b> 올랐고, 그 세 배는 <b>0.19%</b>이며, 이 펀드는 <b>0.05%</b> 올랐습니다. 이렇게 제자리인 날에 그 차이는 반올림 잡음입니다. 장중 저점의 맞춤이 더 정확합니다. 반도체 펀드 저점 2.2%의 세 배에 대해 이 펀드는 약 <b>6.4%</b> 아래까지 갔습니다. 넷째, 주간입니다. 최근 5거래일 약 <b>+27.4%</b>, 지수는 <b>+9.0%</b>입니다. 단순한 세 배인 약 +27.1%보다 조금 많습니다. 매일 움직임의 세 배를 이어 붙이면 약 <b>+28.3%</b>가 나오니 오차는 1포인트 미만이고, 여기 있는 주간 숫자는 모두 근사치입니다. 이 구간은 9월 중순 폭락 바닥에서 세 거래일 지난 곳에서 시작합니다. 폭락 전 금요일부터 재면 약 <b>+20.1%</b>입니다.'
p['news_en'] = [
    {'dt': 'Sep 24', 'tx': '<b>Rose 0.05% to $146.33 — a flat close hiding a 6% hole and a 6% climb.</b> Chip shares opened down more than 2% and recovered to a hair higher; this fund made the same journey at triple size, touching <b>$136.90</b> — down 6.4% — before climbing back. On a day this flat the triple arithmetic is rounding noise: three times the chip fund’s 0.06% is 0.19%, and this delivered 0.05%. The climb back to its 1-year high eased to about <b>+106%</b>.'},
    p['news_en'][0], p['news_en'][1], p['news_en'][2],
]
p['news_ko'] = [
    {'dt': '9월 24일', 'tx': '<b>0.05% 오른 146.33달러 — 6% 구덩이와 6% 등반을 숨긴 제자리 종가입니다.</b> 반도체 주식은 2% 넘게 낮게 출발해 살짝 오른 자리까지 회복했고, 이 펀드는 같은 여정을 세 배 크기로 했습니다. <b>136.90달러</b> — 6.4% 하락 — 까지 닿았다가 되올라온 것입니다. 이렇게 제자리인 날의 세 배 산수는 반올림 잡음입니다. 반도체 펀드 0.06%의 세 배는 0.19%인데 이것은 0.05%를 냈습니다. 1년 최고가로 돌아가는 데 필요한 상승은 약 <b>+106%</b>로 살짝 줄었습니다.'},
    p['news_ko'][0], p['news_ko'][1], p['news_ko'][2],
]
p['verdict_en'] = '<b>What I’d watch — but first, the standing question to ask about this fund’s numbers: what day does the measurement start?</b> The board’s five-day figure, about <b>+27.4%</b>, starts three sessions after the bottom of the mid-September crash. Measured from the Friday before that weekend, the rise is about <b>+20.1%</b>. Both are correct; they describe different owners. <b>Now the calendar.</b> First, <b>next Wednesday, September 30 — Micron’s results and the Fed’s inflation figure on the same day</b>. One is the hardest test yet of the memory story that has driven the chip sector; the other moves the rates that expensive chip shares answer to. Whatever chips decide that day is worth, this fund feels it three times over — in either direction. Second, hold onto what yesterday showed: a day the board calls <b>+0.05%</b> contained a fall of more than 6% and a full recovery before lunch. Days that alternate like that, strung together, are the setting in which the daily reset grinds money away — that is the decay that cost <b>57%</b> in a flat July. The standing arithmetic barely moved: about <b>51.5%</b> below its 1-year high, needing about <b>+106%</b> to get back. If you want the chip bet without the whiplash, Nvidia rose about <b>2.4%</b> over the same five days.'
p['verdict_ko'] = '<b>지켜볼 것 — 그 전에, 이 펀드의 숫자에 늘 던져야 하는 질문부터. 측정이 어느 날 시작되는가?</b> 표의 5일 숫자 약 <b>+27.4%</b>는 9월 중순 폭락 바닥에서 세 거래일 지난 곳에서 시작합니다. 그 주말 전 금요일부터 재면 약 <b>+20.1%</b>입니다. 둘 다 맞고, 서로 다른 보유자를 설명합니다. <b>이제 달력입니다.</b> 첫째, <b>다음 주 수요일 9월 30일 — 마이크론 실적과 연준 물가 수치가 같은 날</b>입니다. 하나는 반도체 업종을 이끌어 온 메모리 이야기의 가장 어려운 시험이고, 다른 하나는 비싼 반도체 주식이 답해야 하는 금리를 움직입니다. 반도체가 그날을 얼마짜리로 정하든, 이 펀드는 그 세 배를 — 어느 방향으로든 — 느낍니다. 둘째, 어제가 보여 준 것을 붙들어 두십시오. 표가 <b>+0.05%</b>라고 부르는 하루 안에 6% 넘는 하락과 점심 전의 완전한 회복이 들어 있었습니다. 그런 엇갈리는 날들이 이어지는 것이 매일 리셋이 돈을 갈아 없애는 환경입니다. 제자리걸음이던 7월에 <b>57%</b>를 가져간 부식이 그것입니다. 항상 붙는 산수는 거의 그대로입니다. 1년 최고가보다 약 <b>51.5%</b> 아래이고, 돌아가려면 약 <b>+106%</b>가 필요합니다. 채찍질 없이 반도체에 걸고 싶다면, 엔비디아는 같은 닷새 동안 약 <b>2.4%</b> 올랐습니다.'
p['plain_en'] = '<b>Read this one carefully — it is by far the riskiest of the five.</b> SOXL is built to move <b>three times</b> as much as chip stocks do, <b>every single day</b>, starting fresh each morning. <b>Yesterday is the perfect illustration: the board says +0.05%, a flat day — and in the first hour it was down more than 6%, because chip stocks opened 2% lower and this triples them.</b> It climbed all the way back only because the market recovered. The past five trading days still show the machine at its best — about <b>+27.4%</b>, three times the chip index’s <b>+9.0%</b> and a little more, because an unbroken run of rising days pays a bonus. But the same machinery charges for every change of direction: it cost <b>57%</b> in July when the overall market was flat, and about <b>17%</b> in one session two weeks ago. The hole above is the thing to hold onto: about <b>51.5%</b> below its best price of the past year, needing a rise of about <b>106%</b> to get back. Next Wednesday brings Micron’s results and the Fed’s inflation figure; whatever chips decide those are worth, this feels it three times over.'
p['plain_ko'] = '<b>이 종목은 찬찬히 읽어 주세요. 다섯 중 단연 가장 위험합니다.</b> SOXL은 반도체 주식이 움직이는 만큼의 <b>세 배</b>를, <b>매일매일</b>, 아침마다 새로 시작하며 움직이도록 만들어졌습니다. <b>어제가 완벽한 예시입니다. 표에는 +0.05%, 제자리 하루라고 적히지만 — 첫 한 시간에는 6% 넘게 내려 있었습니다. 반도체 주식이 2% 낮게 출발했고, 이것은 그 세 배이기 때문입니다.</b> 시장이 회복했기 때문에 전부 되올라온 것뿐입니다. 최근 5거래일은 여전히 이 기계의 가장 좋은 모습입니다. 약 <b>+27.4%</b>로, 반도체 지수 <b>+9.0%</b>의 세 배가 조금 넘습니다. 끊기지 않은 상승 구간이 보너스를 주기 때문입니다. 그러나 같은 기계가 방향이 바뀔 때마다 요금을 걷습니다. 시장이 제자리걸음이던 7월에 <b>57%</b>를, 2주 전에는 한 번의 장에서 약 <b>17%</b>를 가져갔습니다. 붙들어야 할 것은 위에 뚫린 구멍입니다. 지난 1년 최고가보다 약 <b>51.5%</b> 아래이고, 돌아가려면 약 <b>106%</b> 올라야 합니다. 다음 주 수요일에는 마이크론 실적과 연준 물가 수치가 옵니다. 반도체가 그것들을 얼마짜리로 정하든, 이것은 그 세 배로 느낍니다.'
p['bull_en'] = 'For the year it is up about <b>248%</b>, and the past five days still show the machine at its very best: about <b>+27.4%</b> against a simple triple of <b>+27.1%</b>, because on an unbroken run the daily reset compounds in the holder’s favour. That is the only honest version of the case: <b>this fund pays when the direction holds</b>. The demand behind the sector keeps arriving as hard numbers rather than opinion — <b>Intel</b> reported to have more orders than it can build, <b>AMD</b> holding above <b>$1 trillion</b>, <b>South Korea’s</b> chip exports at roughly three times last year’s pace — and <b>Micron reports Wednesday</b>, the moment the memory story can turn into published profits. The tariff truce with China now runs to <b>January 10</b>. The hole above has narrowed from needing <b>+144%</b> a week ago to about <b>+106%</b> now; that is how fast this fund travels when the road is straight.'
p['bull_ko'] = '올해 들어 약 <b>248%</b> 올랐고, 최근 닷새는 여전히 이 기계의 가장 좋은 모습입니다. 단순한 세 배인 <b>+27.1%</b>보다 많은 약 <b>+27.4%</b>입니다. 끊기지 않은 상승 구간에서는 매일 리셋이 보유자에게 유리한 복리로 작동하기 때문입니다. 이것이 이 종목을 좋게 말할 수 있는 유일하게 정직한 방식입니다. <b>이 펀드는 방향이 유지될 때 지불합니다.</b> 업종 뒤의 수요는 의견이 아니라 단단한 숫자로 계속 도착합니다. <b>인텔</b>은 만들 수 있는 양보다 주문이 많다고 전해지고, <b>AMD</b>는 <b>1조 달러</b> 위를 지키고 있으며, <b>한국</b> 반도체 수출은 작년의 세 배쯤 되는 속도입니다. 그리고 <b>수요일 마이크론 실적</b> — 메모리 이야기가 공표된 이익으로 바뀔 수 있는 순간입니다. 중국과의 관세 휴전은 이제 <b>1월 10일까지</b>입니다. 위의 구멍은 일주일 전 <b>+144%</b>가 필요하던 것에서 지금 약 <b>+106%</b>로 좁아졌습니다. 길이 곧을 때 이 펀드가 얼마나 빨리 달리는지 보여 주는 숫자입니다.'
p['bear_en'] = '<b>Yesterday was the small print made visible: a day the board calls +0.05% contained a fall of more than 6% and a climb of more than 6%, before lunch.</b> The close forgave it this time because the direction turned once and held; days that keep alternating are the setting that cost <b>57% in July</b> while the market was flat, and choppy weeks are more common than straight lines. Everything that made the five-day figure wonderful is a coin with two faces: the same reset that compounds a straight run grinds an alternating one. The week’s <b>+27.4%</b> starts three sessions off the crash bottom; from the Friday before the weekend gap the rise is about <b>+20.1%</b>, and anyone who held through that weekend knows charts can hide the worst part. The rate pressure has not lifted — the ten-year has closed at a 2007-high two days running, and every chip reaction to rates lands here tripled. Next Wednesday stacks Micron’s results and the inflation figure on one day, tripled. A holding that can lose 6% before lunch on a “flat” day is not a place to store money — it is a bet with a meter running.'
p['bear_ko'] = '<b>어제는 작은 글씨가 눈에 보이게 된 날이었습니다. 표가 +0.05%라고 부르는 하루 안에, 점심 전까지 6% 넘는 하락과 6% 넘는 등반이 들어 있었습니다.</b> 이번에는 방향이 한 번 돌고 유지됐기 때문에 종가가 용서해 준 것뿐입니다. 계속 엇갈리는 날들이야말로 시장이 제자리이던 <b>7월에 57%</b>를 가져간 환경이고, 출렁이는 주는 곧은 길보다 흔합니다. 5일 숫자를 훌륭하게 만든 모든 것은 양면이 있는 동전입니다. 곧은 구간을 복리로 불리는 그 리셋이, 엇갈리는 구간은 갈아 없앱니다. 주간 <b>+27.4%</b>는 폭락 바닥에서 세 거래일 지난 곳에서 시작합니다. 주말 갭 전 금요일부터 재면 약 <b>+20.1%</b>이고, 그 주말을 버틴 사람은 차트가 가장 나쁜 부분을 숨길 수 있다는 것을 압니다. 금리 압력은 걷히지 않았습니다. 10년물이 이틀 연속 2007년 이후 최고 종가를 썼고, 금리에 대한 반도체의 반응은 여기에 세 배로 떨어집니다. 다음 주 수요일에는 마이크론 실적과 물가 수치가 한 날에 쌓이고, 그것도 세 배입니다. "제자리" 날에 점심 전 6%를 잃을 수 있는 것은 돈을 보관하는 곳이 아닙니다. 미터기가 돌아가는 내기입니다.'

with open('data/market.json', 'w') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
    f.write('\n')
print('part 3 done: nvda + soxl panels')
