#!/usr/bin/env python3
# Part 2: SPX + QQQ panels.
import json

with open('data/market.json') as f:
    d = json.load(f)

p = d['positions']['spx']
p.update({
    'price': '7,704.13',
    'day_arrow': '', 'day_en': '−0.02% yesterday — essentially flat', 'day_ko': '어제 −0.02% — 사실상 제자리', 'day_dir': 'fl',
    'week_arrow': '▲', 'week_en': '≈ +0.9% past five days', 'week_ko': '최근 5거래일 ≈ +0.9%', 'week_dir': 'up',
    'month_arrow': '▲', 'month_en': '≈ +0.2% so far in September', 'month_ko': '9월 들어 ≈ +0.2%', 'month_dir': 'up',
    'drawdown_arrow': '▼', 'drawdown': '≈ 1.2%', 'drawdown_dir': 'dn',
    'drawdown_fact_en': '≈ 1.2%', 'drawdown_fact_ko': '≈ 1.2%',
    'take_en': 'Held steady as rates rose', 'take_ko': '금리 올라도 버팀', 'take_tone': 'c-neu',
    'week_fact_en': 'up ≈ 0.9%', 'week_fact_ko': '≈ 0.9% 상승',
})
p['note_en'] = '<b>Yesterday the market was pushed twice and did not fall.</b> The index closed 1.90 points lower at <b>7,704.13</b> — essentially flat — but the flat close hides a full round trip. In the morning shares fell about half a percent: the ten-year borrowing rate was climbing again, and oil jumped after Iran-allied fighters fired missiles at Saudi Arabia. Then a report landed that American and Iranian negotiators are discussing a step-by-step deal to reopen the <b>Strait of Hormuz</b> — the channel much of the world’s oil passes through — and shares climbed back all afternoon. The government also sold <b>$44 billion</b> of seven-year bonds at midday; demand was on the soft side, but there was no repeat of Wednesday’s bad five-year sale. Still, by the close the ten-year rate stood at about <b>5.18%</b> — a second straight highest finish since <b>2007</b> — and that is the running story under everything: lenders keep asking for more, and so far shares keep refusing to fall much. After the close, <b>Costco</b> — the only one of your five reporting this season — delivered solid results, and the shares barely moved. The index sits about <b>1.2%</b> below its late-August record and is up about <b>12.5%</b> this year.'
p['note_ko'] = '<b>어제 시장은 두 번 떠밀리고도 넘어지지 않았습니다.</b> 지수는 1.90포인트 낮은 <b>7,704.13</b>으로, 사실상 제자리로 마쳤습니다. 그러나 제자리 종가 뒤에는 온전한 왕복 하루가 숨어 있습니다. 아침에는 주가가 0.5%쯤 밀렸습니다. 10년물 차입 금리가 다시 오르고 있었고, 이란과 연계된 무장세력이 사우디아라비아에 미사일을 쏜 뒤 유가가 뛰었습니다. 그러다 미국과 이란 협상단이 세계 원유의 상당량이 지나는 <b>호르무즈 해협</b>을 단계적으로 다시 여는 방안을 논의 중이라는 보도가 나왔고, 주가는 오후 내내 되올랐습니다. 정부는 한낮에 <b>440억 달러</b>의 7년물 국채도 팔았습니다. 수요는 다소 약했지만, 수요일의 나쁜 5년물 판매가 되풀이되지는 않았습니다. 그래도 마감 무렵 10년물 금리는 약 <b>5.18%</b>로 이틀 연속 <b>2007년</b> 이후 최고 종가를 썼습니다. 이것이 모든 것 아래에 깔린 이야기입니다. 빌려주는 쪽은 계속 더 요구하는데, 주가는 아직 크게 물러서기를 거부하고 있습니다. 장 마감 뒤에는 이번 분기 보유 다섯 중 유일하게 실적을 내는 <b>코스트코</b>가 탄탄한 결과를 내놓았고, 주가는 거의 움직이지 않았습니다. 지수는 8월 말 기록보다 약 <b>1.2%</b> 아래에 있고, 올해 들어 약 <b>12.5%</b> 올라 있습니다.'
p['news_en'] = [
    {'dt': 'Sep 24', 'tx': '<b>Closed 1.90 points lower at 7,704.13 — essentially flat, after recovering a morning fall of about half a percent.</b> The turn came on a report that the United States and Iran are discussing a step-by-step reopening of the <b>Strait of Hormuz</b>. The ten-year borrowing rate still closed at about <b>5.18%</b>, a second straight highest finish since 2007, and <b>oil rose a second day</b>. After the close, <b>Costco reported solid results</b>.'},
    p['news_en'][0], p['news_en'][1], p['news_en'][2],
]
p['news_ko'] = [
    {'dt': '9월 24일', 'tx': '<b>1.90포인트 낮은 7,704.13으로 마감 — 사실상 제자리이고, 아침의 0.5%쯤 되는 하락을 되찾은 결과입니다.</b> 전환점은 미국과 이란이 <b>호르무즈 해협</b>을 단계적으로 다시 여는 방안을 논의 중이라는 보도였습니다. 그래도 10년물 차입 금리는 약 <b>5.18%</b>로 이틀 연속 2007년 이후 최고 종가를 썼고, <b>유가는 이틀째 올랐습니다</b>. 장 마감 뒤 <b>코스트코가 탄탄한 실적</b>을 내놓았습니다.'},
    p['news_ko'][0], p['news_ko'][1], p['news_ko'][2],
]
p['verdict_en'] = '<b>What I’d watch first: next week — this one ends quietly, but the next one is crowded.</b> Today brings only a report on factory orders for big-ticket goods just before the open, a consumer-mood reading just after it, and Federal Reserve officials speaking through the day. Then Tuesday an American ban on some Canadian foods takes effect; Wednesday brings both the <b>August inflation figure</b> the Fed watches most and <b>Micron’s results</b>; and next Friday is the <b>September jobs report</b>. Underneath it all sits the bond market: the ten-year rate has now set two straight highest closes since 2007, at about <b>5.18%</b>, and the next Fed decision is <b>October 28</b> — most officials have signalled another rise, and the market prices one as more likely than not. Shares have absorbed the rate climb so far; whether they keep doing so is the month’s real question, and nobody can tell you the answer.'
p['verdict_ko'] = '<b>제가 먼저 볼 것: 다음 주입니다. 이번 주는 조용히 끝나지만, 다음 주는 붐빕니다.</b> 오늘은 개장 직전의 내구재 주문 보고서, 개장 직후의 소비자 심리 수치, 그리고 하루에 걸친 연준 인사들의 발언뿐입니다. 그러다 화요일에는 일부 캐나다산 식품에 대한 미국의 수입 금지가 시행되고, 수요일에는 연준이 가장 눈여겨보는 <b>8월 물가 수치</b>와 <b>마이크론 실적</b>이 함께 나오며, 다음 주 금요일은 <b>9월 고용 보고서</b>입니다. 이 모든 것 아래에 채권시장이 있습니다. 10년물 금리는 이제 이틀 연속 2007년 이후 최고 종가를 썼고 — 약 <b>5.18%</b> — 다음 연준 결정은 <b>10월 28일</b>입니다. 위원 대부분이 추가 인상 신호를 보냈고, 시장도 인상 가능성을 더 높게 봅니다. 주가는 지금까지 금리 상승을 견뎌 왔습니다. 계속 견딜지가 이번 달의 진짜 질문이고, 그 답은 아무도 말해 줄 수 없습니다.'
p['facts'][3] = {'en': 'Fear gauge', 'ko': '공포 지수', 'v_en': '15.67 — up two days running, still low for the year', 'v_ko': '15.67 — 이틀 연속 상승, 그래도 올해 기준 낮은 수준'}
p['plain_en'] = 'This one number tracks the 500 largest American companies. It is the simplest answer to "how did the market do?" <b>Yesterday it closed essentially flat at 7,704.13</b> — but only after falling about half a percent in the morning and climbing all the way back on news that the United States and Iran are discussing reopening the oil shipping strait. The ten-year borrowing rate still finished at about <b>5.18%</b>, its second straight highest close since 2007. The index sits about <b>1.2%</b> below its record and is up about <b>12.5%</b> this year. The two set-piece events this month pointed at — the China summit and Costco’s results — have now both passed without damage; the bond market is the story that has not passed.'
p['plain_ko'] = '이 숫자 하나가 미국에서 가장 큰 회사 500개를 대표합니다. "시장이 어땠나?"에 대한 가장 간단한 답입니다. <b>어제는 7,704.13으로 사실상 제자리 마감이었습니다.</b> 다만 아침에 0.5%쯤 내렸다가, 미국과 이란이 원유 수송로를 다시 여는 방안을 논의 중이라는 소식에 전부 되오른 결과입니다. 10년물 차입 금리는 약 <b>5.18%</b>로 이틀 연속 2007년 이후 최고 종가를 썼습니다. 지수는 기록보다 약 <b>1.2%</b> 아래, 올해 들어 약 <b>12.5%</b> 위에 있습니다. 이번 달이 가리켜 온 두 개의 큰 행사 — 중국 정상회담과 코스트코 실적 — 는 이제 상처 없이 지나갔습니다. 지나가지 않은 이야기는 채권시장입니다.'
p['bull_en'] = 'The test keeps getting harder, and the market keeps passing it. Yesterday the ten-year rate set a second straight highest close since 2007 and oil rose again — and the index finished flat, recovering its whole morning fall. The week’s three big bond sales are done; the China summit ended in friendly words and a tariff truce extended to <b>January 10</b>; Costco’s solid report drew a calm reaction. The past five trading days are up about <b>0.9%</b>, the record is about <b>1.2%</b> away, and the year’s gain is about <b>12.5%</b> — earned through a rate rise, an oil spike and a chip scare.'
p['bull_ko'] = '시험은 계속 어려워지는데, 시장은 계속 통과하고 있습니다. 어제 10년물 금리가 이틀 연속 2007년 이후 최고 종가를 쓰고 유가도 다시 올랐지만, 지수는 아침 하락을 전부 되찾고 제자리로 마쳤습니다. 이번 주 세 번의 대형 국채 판매는 끝났고, 중국 정상회담은 우호적인 말과 <b>1월 10일까지</b> 연장된 관세 휴전으로 마무리됐으며, 코스트코의 탄탄한 실적은 차분하게 받아들여졌습니다. 최근 5거래일은 약 <b>0.9%</b> 상승, 기록까지는 약 <b>1.2%</b>, 올해 수익은 약 <b>12.5%</b>입니다. 금리 인상과 유가 급등과 반도체 공포를 다 겪으며 얻은 숫자입니다.'
p['bear_en'] = '<b>Rates keep rising and shares keep not falling — one of those two usually gives.</b> The ten-year has closed at a fresh 2007-high two days running, the thirty-year was reported at its highest since 2004, and the Fed is still expected to raise again — the next decision is October 28. Yesterday afternoon’s calm rests on talks that have produced no deal yet: if the Iran negotiations stall, oil and rates take back what the report gave. Oil has already risen two days in a row. And next Wednesday brings the inflation figure the Fed watches most — a hot number would put the whole argument back on the table at once.'
p['bear_ko'] = '<b>금리는 계속 오르고 주가는 계속 내리지 않고 있습니다. 보통은 둘 중 하나가 무너집니다.</b> 10년물은 이틀 연속 2007년 이후 최고 종가를 새로 썼고, 30년물은 장중 2004년 이후 최고로 보도됐으며, 연준은 여전히 또 올릴 것으로 예상됩니다. 다음 결정은 10월 28일입니다. 어제 오후의 차분함은 아직 아무 합의도 내놓지 못한 협상 위에 서 있습니다. 이란 협상이 멈추면, 보도가 준 것을 유가와 금리가 도로 가져갑니다. 유가는 이미 이틀 연속 올랐습니다. 그리고 다음 주 수요일에는 연준이 가장 눈여겨보는 물가 수치가 나옵니다. 뜨거운 숫자 하나면 논쟁 전체가 한꺼번에 되살아납니다.'

p = d['positions']['qqq']
p.update({
    'price': '$741.10',
    'day_arrow': '', 'day_en': '−0.01% yesterday — flat', 'day_ko': '어제 −0.01% — 제자리', 'day_dir': 'fl',
    'week_arrow': '▲', 'week_en': '≈ +3.4% past five days', 'week_ko': '최근 5거래일 ≈ +3.4%', 'week_dir': 'up',
    'month_arrow': '▲', 'month_en': '≈ +3.4% so far in September', 'month_ko': '9월 들어 ≈ +3.4%', 'month_dir': 'up',
    'drawdown_arrow': '▼', 'drawdown': '≈ 1.0%', 'drawdown_dir': 'dn',
    'drawdown_fact_en': '≈ 1.0%', 'drawdown_fact_ko': '≈ 1.0%',
    'take_en': 'About 1% from its record', 'take_ko': '기록까지 약 1%', 'take_tone': 'c-neu',
    'week_fact_en': 'up ≈ 3.4%', 'week_fact_ko': '≈ 3.4% 상승',
})
p['note_en'] = '<b>Yesterday the fund closed a penny lower at $741.10 — flat, at the end of a day that was anything but.</b> It opened down almost 1%, followed the whole market back up on the report of US-Iran talks over reopening the oil strait, and finished where it started. Chip shares made the same round trip in a bigger arc: down more than 2% early, a hair higher by the close, their two-day slide stopped. What did not stop was the rate climb — the ten-year closed at about <b>5.18%</b>, a second straight highest finish since 2007, and expensive technology shares feel that first. The White House summit ended with a state dinner seating technology chiefs at the head table — <b>Nvidia’s and AMD’s among them</b> — and <b>no announcement on chips or exports in either direction</b>: the hope that helped power this month’s run neither paid out nor was called in. The fund sits about <b>1.0%</b> below its record and is up about <b>3.4%</b> in September. The next hard test has a date: <b>Micron reports next Wednesday</b>, the first real numbers behind the memory story that led the whole rise.'
p['note_ko'] = '<b>어제 펀드는 1센트 낮은 741.10달러, 제자리로 마쳤습니다. 그러나 하루는 전혀 제자리가 아니었습니다.</b> 1% 가까이 낮게 출발했다가, 미국과 이란이 원유 수송로를 다시 여는 방안을 논의 중이라는 보도에 시장 전체와 함께 되올라 출발점에서 끝났습니다. 반도체 주식은 같은 왕복을 더 큰 폭으로 했습니다. 장 초반 2% 넘게 내렸다가 마감에는 살짝 올랐고, 이틀 이어진 하락은 멈췄습니다. 멈추지 않은 것은 금리입니다. 10년물이 약 <b>5.18%</b>로 이틀 연속 2007년 이후 최고 종가를 썼고, 비싼 기술주가 그것을 가장 먼저 느낍니다. 백악관 정상회담은 기술 기업 대표들 — <b>엔비디아와 AMD 대표 포함</b> — 을 헤드테이블에 앉힌 국빈 만찬으로 끝났고, <b>반도체와 수출에 대해서는 어느 방향으로도 발표가 없었습니다.</b> 이번 달 상승을 도운 기대는 지급되지도, 회수되지도 않은 채 끝난 것입니다. 펀드는 기록보다 약 <b>1.0%</b> 아래, 9월 들어 약 <b>3.4%</b> 위에 있습니다. 다음 시험에는 날짜가 있습니다. <b>다음 주 수요일 마이크론 실적</b> — 이번 상승 전체를 이끈 메모리 이야기 뒤의 첫 진짜 숫자입니다.'
p['news_en'] = [
    {'dt': 'Sep 24', 'tx': '<b>Closed a penny lower at $741.10 — flat, after being down almost 1% in the morning.</b> The recovery came with the whole market, on a report of US-Iran talks about reopening the oil strait; chip shares ended a hair higher after a 2% early fall. The summit produced <b>no chip announcement either way</b>. The ten-year rate closed at about <b>5.18%</b>, a second straight 2007-high. <b>Costco reported after the close</b>; the reaction was calm.'},
    p['news_en'][0], p['news_en'][1], p['news_en'][2],
]
p['news_ko'] = [
    {'dt': '9월 24일', 'tx': '<b>1센트 낮은 741.10달러로 마감 — 제자리이지만, 아침에는 1% 가까이 내려 있었습니다.</b> 회복은 미국과 이란이 원유 수송로 재개방을 논의 중이라는 보도에 시장 전체와 함께 왔고, 반도체는 장 초반 2% 하락에서 살짝 오른 채 마쳤습니다. 정상회담은 <b>반도체에 대해 어느 방향의 발표도</b> 내놓지 않았습니다. 10년물 금리는 약 <b>5.18%</b>로 이틀 연속 2007년 이후 최고였습니다. <b>장 마감 뒤 코스트코가 실적</b>을 냈고, 반응은 차분했습니다.'},
    p['news_ko'][0], p['news_ko'][1], p['news_ko'][2],
]
p['verdict_en'] = '<b>What I’d watch first: Micron’s results next Wednesday, September 30 — the first hard numbers behind the memory story that led this fund’s September run.</b> Memory is where the chip strength keeps coming from, Micron’s shares have almost quadrupled this year, and the report lands the same morning as the <b>August inflation figure</b> the Fed watches most — the heaviest day of next week, and it reaches this fund from both sides. Second, <b>rates</b>: the ten-year has set two straight highest closes since 2007, and the most expensive shares — which is what this fund holds — answer to rates first. Third, the record: about <b>1.0%</b> away. An ordinary good day still reaches it; a hot inflation number pushes it away. The China summit passed without chip news in either direction, so the argument returns to the two things it never really left: demand and the price of money.'
p['verdict_ko'] = '<b>제가 먼저 볼 것: 다음 주 수요일, 9월 30일 마이크론 실적입니다. 이 펀드의 9월 상승을 이끈 메모리 이야기 뒤의 첫 확실한 숫자입니다.</b> 반도체의 힘은 계속 메모리에서 나오고 있고, 마이크론 주가는 올해 네 배 가까이 올랐으며, 이 실적은 연준이 가장 눈여겨보는 <b>8월 물가 수치</b>와 같은 날 아침에 나옵니다. 다음 주 가장 무거운 날이고, 이 펀드에는 양쪽에서 닿습니다. 둘째, <b>금리</b>입니다. 10년물이 이틀 연속 2007년 이후 최고 종가를 썼고, 가장 비싼 주식들 — 이 펀드가 담고 있는 바로 그것 — 이 금리에 가장 먼저 답합니다. 셋째, 기록입니다. 약 <b>1.0%</b> 남았습니다. 평범한 좋은 하루면 닿고, 뜨거운 물가 숫자 하나면 멀어집니다. 중국 정상회담은 반도체 소식 없이 지나갔으니, 논쟁은 원래 있던 두 가지로 돌아갑니다. 수요, 그리고 돈의 값입니다.'
p['plain_en'] = 'This fund holds the 100 biggest technology companies — Apple, Microsoft, Nvidia and their neighbours — so it is the purest bet among your five on technology keeping its promises. <b>Yesterday it closed a penny lower at $741.10 — flat — after falling almost 1% in the morning and recovering it all.</b> Over five trading days it is up about <b>3.4%</b>, and it sits about <b>1.0%</b> below its all-time high. The month’s two big events — the China summit and Costco’s results — have passed; the next dated test for this fund is <b>Micron’s results next Wednesday</b>, the memory maker whose enormous year has been carrying the chip story.'
p['plain_ko'] = '이 펀드는 애플, 마이크로소프트, 엔비디아 같은 가장 큰 기술 기업 100개를 담고 있습니다. 보유 다섯 중 기술이 약속을 지킨다는 데 거는 가장 순수한 베팅입니다. <b>어제는 1센트 낮은 741.10달러, 제자리로 마쳤습니다. 아침에 1% 가까이 내렸다가 전부 되찾은 결과입니다.</b> 최근 5거래일로는 약 <b>3.4%</b> 올라 있고, 사상 최고가보다 약 <b>1.0%</b> 아래에 있습니다. 이번 달의 두 큰 행사 — 중국 정상회담과 코스트코 실적 — 는 지나갔습니다. 이 펀드의 다음 날짜 박힌 시험은 <b>다음 주 수요일 마이크론 실적</b>입니다. 거대한 한 해를 보내며 반도체 이야기를 이끌어 온 메모리 회사입니다.'
p['bull_en'] = 'Five trading days up about <b>3.4%</b>, the record about 1% away, and the demand story underneath is intact: memory chips are short, South Korea’s chip exports are running at roughly three times last year’s pace, and the tariff truce with China now runs to <b>January 10</b>. The rate scare has now thrown two of its hardest days at this fund — the worst bond close since 2007, twice in a row — and taken back less than 1% in total. Micron’s results on Wednesday are the chance for the memory story to turn from enthusiasm into published numbers.'
p['bull_ko'] = '최근 5거래일 약 <b>+3.4%</b>, 기록까지 약 1%, 그리고 그 아래의 수요 이야기는 그대로입니다. 메모리 반도체는 부족하고, 한국의 반도체 수출은 작년의 세 배쯤 되는 속도로 달리고 있으며, 중국과의 관세 휴전은 이제 <b>1월 10일까지</b>입니다. 금리 공포는 가장 어려운 이틀 — 2007년 이후 최악의 채권 종가, 그것도 연이틀 — 을 이 펀드에 던졌는데, 도로 가져간 것은 다 합쳐 1%가 안 됩니다. 수요일 마이크론 실적은 메모리 이야기가 열광에서 공표된 숫자로 바뀔 기회입니다.'
p['bear_en'] = '<b>Everything expensive answers to rates, and rates have not stopped.</b> The ten-year closed at a fresh 2007-high two days running, and the Fed is expected to raise again in October. The summit this month’s rally partly leaned on has come and gone without delivering anything on chips — the hope is spent, and the price is still up about <b>3.4%</b> on the month. Micron on Wednesday cuts both ways: after a year in which the shares almost quadrupled, even good results can disappoint a price this eager. And the fund remains a concentrated bet on a handful of AI-linked companies near record prices, in the face of the dearest borrowing costs in nineteen years.'
p['bear_ko'] = '<b>비싼 것은 모두 금리에 답해야 하는데, 금리는 멈추지 않았습니다.</b> 10년물이 이틀 연속 2007년 이후 최고 종가를 새로 썼고, 연준은 10월에 또 올릴 것으로 예상됩니다. 이번 달 상승이 일부 기대 온 정상회담은 반도체에 아무것도 내놓지 않고 지나갔습니다. 기대는 소진됐는데, 값은 여전히 이번 달 약 <b>3.4%</b> 올라 있습니다. 수요일 마이크론은 양날입니다. 주가가 올해 네 배 가까이 오른 뒤라, 좋은 실적도 이렇게 조급한 값에는 실망이 될 수 있습니다. 그리고 이 펀드는 여전히 기록 부근 값의 AI 관련 회사 몇 곳에 집중된 베팅입니다. 19년 만에 가장 비싼 차입 비용을 마주한 채로 말입니다.'

with open('data/market.json', 'w') as f:
    json.dump(d, f, ensure_ascii=False, indent=2)
    f.write('\n')
print('part 2 done: spx + qqq panels')
